project_id = "pqzhnpgwhcuxaduvxans"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.ai-chatbot]
verify_jwt = false

[functions.check-signup-email]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false